name: Unit Tests

on:
  pull_request:
  push:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requirements
        # pip install -r ./requirements/local.in
        run: |
          python -m pip install --upgrade pip
          echo "someday I will install requirements."

      - name: secure_logger Unit tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          echo "I someday hope to become a remotely executed Python unit test suite."

      - name: setup.py tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python -m unittest setup_test
